Updated pull, push, backup. Added bookmarks

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -7,29 +7,31 @@
 #    r  - recurse into subdirectories
 #    x  - exclude these (in this case hidden files/directories) 
 
-if [ "$BACKUPS" == "" ] ; then
-    echo "Error: BACKUPS environment variable not set."    
-    exit
-fi
+fatal()     { echo "fatal: $*" >&2; exit 1; }                   # exit with message and generic error code   
+pass-item() { pass-cli item view pass://Personal/Desktop/$1; }  # Get value from Proton Pass Desktop 
+check-set() { [ "$1" == "" ] && fatal "$2 not set."; }          # Confirm we have values
+do-folder() { echo "Zipping up $2" >> $log ; zip -FSr $1/$2.zip $home/$2 -x .*   >> $log ; }  
 
-log=$BACKUPS/backup-log.txt 
+backups=$(pass-item backups)
+remote=$(pass-item remote)
+password=$(pass-item sshpass)
+home=$(pass-item home)
 
-do-folder()  { echo "Zipping up $1" >> $log ; zip -FSr $BACKUPS/$1.zip $HOME/$1 -x .*   >> $log ; }  
+check-set "$backups"  "backups"
+check-set "$remote"   "remote"
+check-set "$password" "sshpass"
+check-set "$home"     "home"
+
+log=$backups/backup-log.txt 
 
 echo "Backup Started" > $log
 
-for d in $(find $HOME -maxdepth 1 -not -path '*/.*' -type d) ; do
-    if [ "$d" != "$HOME" ]; then
+for d in $(find $home -maxdepth 1 -not -path '*/.*' -type d) ; do
+    if [ "$d" != "$home" ]; then
 		if [ ! -z "$( ls -A $d )" ]; then
-			do-folder $(basename $d)
+			do-folder $backups $(basename $d)
 		fi	
     fi
 done
 
-if [ "$BACKUP_REMOTE" != "" ] ; then
-	if [ "$SSHPASS" == "" ] ; then
-	    echo "Error: SSHPASS environment variable not set."    
-    else
-		sshpass -e rsync -utp $BACKUPS/* $BACKUP_REMOTE
-	fi
-fi
+sshpass -p $password rsync -utp $backups/* rsync://$remote/$(basename $backups)
